### ISSUE TITLE
Adjust the placement of Google map error icon on a admin form field

### ISSUE THREAD

**Issue by TheLazzziest** [furious-luke/django-address#107]
It just overlaps on a input tag. [Preview](https://i.imgur.com/f2BSQXb.png)

**Comment by banagale** [comment]
Thanks for pointing this out. I've added this to our next triage milestone for validation and fix.

**Comment by banagale** [comment]
Possible duplicate of #79.

**Comment by banagale** [comment]
This wasn't a duplicate, but the source issue describing the fix handled by #79.

#79 is now merged. Thanks @TheLazzziest for the initial report.
