### ISSUE TITLE
Readme is inconsistent

### ISSUE THREAD

**Issue by curtisstpierre** [furious-luke/django-address#111]
pip install django-address

Then, add address to your INSTALLED_APPS list in settings.py:

INSTALLED_APPS = [
    ... 
    'django_filters',
]

I assume address is what should be in installed apps not django_filters

**Comment by banagale** [comment]
@curtisstpierre Thanks for the heads-up. This will be fixed in the next release.

Please see https://github.com/furious-luke/django-address/issues/108
