### ISSUE TITLE
Restrict Autocomplete to Specific Countries

### ISSUE THREAD

**Issue by masaruduy** [furious-luke/django-address#113]
Thanks for you great app you made.

Is there a way to restrict the autocomplete results to certain countries? I've found this setting on 
https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-multiple-countries:
     autocomplete.setComponentRestrictions(
            {'country': ['us', 'pr', 'vi', 'gu', 'mp']});

Not sure how it could be used together with your code though.
Can you please advise?

Thanks!

**Comment by banagale** [comment]
@masaruduy 

Currently there is no way to pass this option in without modifying the package.  However, I was able to achieve this by modifying the `address.js` file.

Here's [the line in question](https://github.com/furious-luke/django-address/blob/c5df849e73ff9eac93764cde6dff9adbdbb9de96/address/static/address/js/address.js#L7).

Add the countries you want to a country property like this:

```
$(function () {
	$('input.address').each(function () {
		var self = $(this);
		var cmps = $('#' + self.attr('name') + '_components');
		var fmtd = $('input[name="' + self.attr('name') + '_formatted"]');
		self.geocomplete({
			**country: ['IT', 'US'],**
			details: cmps,
			detailsAttribute: 'data-geo'		
...
```

And you get only those countries:

<img width="521" alt="Screen Shot 2020-06-17 at 12 39 26 PM" src="https://user-images.githubusercontent.com/1409710/84942454-b7e4d900-b097-11ea-891b-27b5ba3f842f.png">

I'm closing this for now, but if it comes up again we can look at adding it as a feature.
