### ISSUE TITLE
Address admin class has name in search_fields

### ISSUE THREAD

**Issue by pyarun** [furious-luke/django-address#130]
Address Model does not have a `name` field. But django admin model has `name` in `search_fields`.

This causes Error in Admin when we search.
```
Cannot resolve keyword 'name' into field. Choices are: formatted, id, latitude, locality, locality_id, longitude, raw, route, street_number
```

**Comment by banagale** [comment]
Thanks for the report, @pyarun.

This looks like a 10 year old mistake in `django-address.address.admin`

[Here's the line.](https://github.com/furious-luke/django-address/blob/f418af9ed38939ad77590bedbf99bdd63f54fbb2/address/admin.py#L35)

[Here are the valid fields](https://github.com/furious-luke/django-address/blob/f418af9ed38939ad77590bedbf99bdd63f54fbb2/address/models.py#L238), what were you hoping to search on here?

**Comment by pyarun** [comment]
I think raw, route, and street_number are good candidates. 

If you agree, I will see if I can fix and create an MR.

**Comment by banagale** [comment]
@pyarun. I agree those are good candidates. If you'd like to create a PR, for this here #130, I'd be happy to review and merge. If you have time to add tests, they're welcome but not absolutely necessary.  I'll push this to next release for now.

**Comment by pyarun** [comment]
I didn't see any test cases for admin, and I have never written a test for admin, so not sure how to write it. 
So i just fixed this issue in admin.

**Comment by banagale** [comment]
@pyarun, it looks like there are ways to test modeladmin but it is for more sophisticated operations. I tested your fix and it is good. Thank you.
