### ISSUE TITLE
Update jQuery version, Discuss jQuery loading conflict and `JQUERY_URL` setting in documentation

### ISSUE THREAD

**Issue by jeffykle** [furious-luke/django-address#134]
This package loads an old version of JQuery with the {{ form.media }} template tag. It was causing conflicts with the version of JQuery that I was using, so to alleviate this, I set `JQUERY_URL = False` in **settings.py**. 

See: https://github.com/furious-luke/django-address/blob/master/address/widgets.py

**Comment by banagale** [comment]
Thanks for the note, @jeffykle.  Which version of jQuery are you using?  Can you describe the page where you're loading one version and this is loading a second? Are you just doing a normal import of the library in the HEAD?

 Some to-dos for this:

*   Find version of jQuery in use --- [It is 2.2.0](https://github.com/furious-luke/django-address/blob/50b3033b84f9f9e0676f2e49b6db156356abfa59/address/widgets.py#L16)
*   Find recent stable or LTS version to consider updating to
    *   Check for compatibility with d-a plugin
    *   If compatible, update jquery version

**Comment by jeffykle** [comment]
I'm using the current stable release 3.5.1
Would it be better to not include jQuery and rather instruct the user to load the supported version in their page? I think most users would also be using jQuery already for other purposes as well. 

I'm working with django and I load it in base.html so it's available on every page.

**Comment by banagale** [comment]
Hey @jeffykle 

To ensure the package works out-of-the-box, I think it is okay to include making the call. But I also agree it is a pain to have it conflict with loading it elsewhere, which is common with templating.

At the very least I think this ticket points out:

1.   It is time to update the jQuery version used by this package!
2.  It should be more clear in the docs how to turn off this package's loading.

I'm renaming this ticket to better reflect this task, and will include the changes in the next update.

**Comment by banagale** [comment]
Rather than put more time into supporting jQuery, I think we should focus on #139, which has the intent of eliminating jQuery as a dependency.
