### ISSUE TITLE
Extract Lat and Long coordinates form address?

### ISSUE THREAD

**Issue by felipepardo87587** [furious-luke/django-address#137]
Hey thanks for this great work!

I was wondering if it's possible to extend this to extract the Lat and Long from the address to put it on a Map? 
I am using this as a simple location input and sometimes the sites I want to add have no specific address, so I need to use the coordinates. Also it would be nice to select the location from  a map (optionally)

I sort of tried to do it myself but it's definitely outside my scope of knowledge ;)

**Comment by banagale** [comment]
Hello Felipe, thanks for the praise and question.

As you noted, Django Address does get the latitude and longitude from Google when it makes its initial query and they are stored in the django database.  Here's a quick look at how the result using the django admin of the example site included with this library:

![](https://user-images.githubusercontent.com/1409710/96348256-44120780-105c-11eb-8c03-1b884aa3a838.png)

It sounds like what you want to do is have one or two form fields that can take lat and lng and first store them as the closest address. 

Then as a follow-up, if you could say, drag and drop a pin and have a way to store that as an address that would be helpful too.  

Do I have those features right? 

This library doesn't offer these at this time but it certainly could.

**Comment by felipepardo87587** [comment]
Thanks for the quick response!
What I'm trying to achieve is to give the end user the ability to select a location by:
1. Typing the address and using the autocomplete feature, and then taking the LAT and LNG values from that to update the map point.
OR 
2. Selecting a point in the Map and finding a matching address or the nearest one to those coordinates. I can do that using [django-location-field](https://django-location-field.readthedocs.io/en/latest/formfields.html).
I guess I could extract those from the Address LAT and LNG coordinates. I will try it and let you know, thanks again!

**Comment by banagale** [comment]
@felipepardo87587 

Your 1. can be accomplished, since the lat and lon are indeed extracted from google maps api at the time auto complete is performed and saved in the Address model once save is performed.

Hopefully, you figured out how to get what you need, though I do take this as a possible sign of a good example to add to the docs in the future.

I'm going to close this for now, please feel free to reply if you have further questions and I'll reopen the issue.
