### ISSUE TITLE
Use tox to test against various Python versions

### ISSUE THREAD

**Issue by furious-luke** [furious-luke/django-address#151]
We've still got some Python compatibility code in the code, and I think it's worth ensuring our tests pass with both Python 2 and 3. `tox` can help us setup these tests locally, and integrate them into our CI scripts.

**Comment by furious-luke** [comment]
So, it looks like the code no longer supports Python 2 (depends on features of Django v2+, which are Python 3.5+ only). So, we'd probably want to run tox against only the relevant Python 3 versions, and remove any Python 2 backwards compatible code.

**Comment by banagale** [comment]
I seem to remember debating whether to continue supporting Python 2, but then finding that some 3+ dependency had existed for some time anyway. I searched and couldn't find the notes about it, but I also did not scrub for code indicating support for 2.

**Comment by furious-luke** [comment]
Yeah it looked like we were trying to support Python 2, but I'm pretty comfortable dropping support for it, especially given the code would have actually been throwing errors for anyone using Python 2 for quite a while now.

**Comment by banagale** [comment]
Ya, that was my determination. I was hemming and hawing over it and then saw that it was a moot point already.

I think I had this conversation publicly but alas haven't put my hand on it.
