### ISSUE TITLE
Use Docker for example site

### ISSUE THREAD

**Issue by furious-luke** [furious-luke/django-address#155]
Running the example site in a Docker container will make spinning up reproducible end-to-end tests much easier.

**Comment by banagale** [comment]
Should we include instructions for running the example with docker in the example readme, or is this intended largely to facilitate automated testing? Current [specifies virtualenv](https://github.com/furious-luke/django-address/blob/master/example_site/README.md#create-virtual-environment).

**Comment by furious-luke** [comment]
@banagale Yep, I'd included details in the README, but hadn't merged them yet. They should be visible now.
