### ISSUE TITLE
Register to PyPI

### ISSUE THREAD

**Issue by AbdelBa** [furious-luke/django-address#16]
Please, add this package to PyPI.
I want to make one-step install in my application via pip requirements.txt

Thanks

**Comment by furious-luke** [comment]
Hi there,

No worries, I'll register asap. In the mean time, you should be able to install with `requirements.txt` using a line something like:
```
git+https://github.com/furious-luke/django-address
```

**Comment by furious-luke** [comment]
Ok, I've registered and uploaded to PyPI. Please let me know if you encounter any problems with it.
