### ISSUE TITLE
Include serializers for usage inside rest framework

### ISSUE THREAD

**Issue by devidw** [furious-luke/django-address#172]
When building REST APIs with [Django rest framework](https://www.django-rest-framework.org/community/third-party-packages/), it would be cool to be able to import predefined serializes from django-address like:

```py
from address.serializers import AddressSerialzer, LocalitySerializer, StateSerializer, ContrySerializer
```

Such serializers could look something like: 

```py
from rest_framework import serializers
from address.models import Address, Locality, State, Country


class ContrySerializer(serializers.ModelSerializer):
    """
    Serializer for Country model
    """

    class Meta:
        model = Country
        fields = "__all__"


class StateSerializer(serializers.ModelSerializer):
    """
    Serializer for State model
    """

    country = ContrySerializer()

    class Meta:
        model = State
        fields = "__all__"


class LocalitySerializer(serializers.ModelSerializer):
    """
    Serializer for Locality model
    """

    state = StateSerializer()

    class Meta:
        model = Locality
        fields = "__all__"


class AddressSerialzer(serializers.ModelSerializer):
    """
    Serializer for Address model
    """

    locality = LocalitySerializer()

    class Meta:
        model = Address
        fields = "__all__"
```

This way including the `AddressSerialzer` inside a serializer of a custom model in the API the response would include all nested data instead of only the address ID.

```json
"address": {
    "id": 1,
    "locality": {
        "id": 1,
        "state": {
            "id": 1,
            "country": {
                "id": 1,
                "name": "Australia",
                "code": "AU"
            },
            "name": "Victoria",
            "code": "VIC"
        },
        "name": "Northcote",
        "postalCode": "3070"
    },
    "streetNumber": "1",
    "route": "Somewhere Ave",
    "raw": "1 Somewhere Ave, Northcote, VIC 3070, AU",
    "formatted": "1 Somewhere Ave, Northcote, Victoria 3070, Australia",
    "latitude": null,
    "longitude": null
},
```

**Comment by furious-luke** [comment]
Hi @devidw! Thanks for the suggestion, it's very much appreciated.

While it's certainly tempting to include things like DRF serializers (and possibly viewsets), I believe it falls outside the responsibility of Django Address. It makes the assumption that users of Django Address are using DRF and not some other API framework (for example, Graphene, or Strawberry). We could potentially be adding dependencies to packages that are of no concern or use to consumers of Django Address (someone using Strawberry GraphQL is unlikely to want to install DRF).

Creating serializers for models in DRF is pretty easy, as you've shown in your issue above; I think it's reasonable to leave defining API interfaces to consumers of Django Address.

**Comment by devidw** [comment]
@furious-luke Mhm yeah actually true, sounds understandable. Thanks for taking the time and pointing this out. 🙌
