### ISSUE TITLE
Error installing version 0.2.7 due to incorrect metadata

### ISSUE THREAD

**Issue by dancergraham** [furious-luke/django-address#175]
Hello, 
Thank you for this library!  Unfortunately it looks like the latest release includes an error in the metadata, possibly because the version number in `pyproject.toml` does not match that in `setup.py`... error message from `pip` below:  

WARNING: Requested django-address==0.2.7 from https://files.pythonhosted.org/packages/31/b3/0a48c58bbc43f26c2ff5f96028edccc94e5214950185d4fb6887fc9b6ab9/django-address-0.2.7.tar.gz#sha256=e40a77d0d11c301ce4b6713de05842b3aad6f9ef03a721e5b3ad076142d9b21d (from -r requirements.txt (line 5)), but installing version 0.2.6
#0 5.377 Discarding https://files.pythonhosted.org/packages/31/b3/0a48c58bbc43f26c2ff5f96028edccc94e5214950185d4fb6887fc9b6ab9/django-address-0.2.7.tar.gz#sha256=e40a77d0d11c301ce4b6713de05842b3aad6f9ef03a721e5b3ad076142d9b21d (from https://pypi.org/simple/django-address/): Requested django-address==0.2.7 from https://files.pythonhosted.org/packages/31/b3/0a48c58bbc43f26c2ff5f96028edccc94e5214950185d4fb6887fc9b6ab9/django-address-0.2.7.tar.gz#sha256=e40a77d0d11c301ce4b6713de05842b3aad6f9ef03a721e5b3ad076142d9b21d (from -r requirements.txt (line 5)) has inconsistent version: filename has '0.2.7', but metadata has '0.2.6'
#0 5.378 ERROR: Could not find a version that satisfies the requirement django-address==0.2.7 (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7)
#0 5.378 ERROR: No matching distribution found for django-address==0.2.7

**Comment by furious-luke** [comment]
You're correct, my apologies, I've just updated the metadata in version 0.2.8. Thanks for the report!
