### ISSUE TITLE
Adress field doesn't respect initial data

### ISSUE THREAD

**Issue by davidbernick** [furious-luke/django-address#18]
Hi!

I get a record from a database. I think put that into an array to pre-populate a form. Most fields work fine. The AddressField data, though, doesn't display the initial text (address.raw). Print statements show address.raw spitting out the right info, but the form shows the usual default as the initial value. 

```
            pa = PatientApplication.objects.get(uuid=uuid)
            data={
                  "patientaddress":pa.patient.patientaddress1.raw,
                  "patientphone":pa.patient.patientphone
                  }
            form(data)
```

**Comment by furious-luke** [comment]
Hi David,

A couple of things. Firstly, is your intention to be giving the form GET or POST data for validation? Or to give it initial values? From your code snippet above it looks like you're giving GET or POST data, but you say your providing initial values. If you are intending on giving initial values, you should specify them like:

```
form(initial=data)
```

Secondly, is there any reason to give the raw address value as opposed to the address object itself? The `AddressWidget` prefers to receive address objects, as it can then properly determine the various components of an address. If the a raw value is given those components will not be returned, even if they are previously available.

Cheers,
Luke
