### ISSUE TITLE
unable to use two AddressField in one Model 

### ISSUE THREAD

**Issue by k0ssi** [furious-luke/django-address#21]
Hi,

i created a Model like this:

```
class Company(models.Model):
    name = models.CharField(max_length=255)
    address = AddressField()
    billingAddress = AddressField(blank=True, null=True)
```

which results in the following error if i try to create the Migration Files.

```
python manage.py makemigrations
SystemCheckError: System check identified some issues:

ERRORS:
usermanager.Company.address: (fields.E304) Reverse accessor for 'Company.address' clashes with reverse accessor for 'Company.billingAddress'.
	HINT: Add or change a related_name argument to the definition for 'Company.address' or 'Company.billingAddress'.
usermanager.Company.billingAddress: (fields.E304) Reverse accessor for 'Company.billingAddress' clashes with reverse accessor for 'Company.address'.
	HINT: Add or change a related_name argument to the definition for 'Company.billingAddress' or 'Company.address'.
```

**Comment by furious-luke** [comment]
Hello!

The problem you're seeing is a result of a clash between the related field names that get created on the address model. You can have two address fields on the same model by specifying unique related names.  [Here is the Django documentation](https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.ForeignKey.related_name) on setting related names.

For your particular setup, if you don't need to use the related names, you could try something like this:
```python
class Company(models.Model):
    name = models.CharField(max_length=255)
    address = AddressField(related_name='+')
    billingAddress = AddressField(related_name='+', blank=True, null=True)
```

If you would like to access your company models from the address models, then you can remove *one* of the related name specifications.

Cheers,
Luke

**Comment by k0ssi** [comment]
works fine. 
Thanks for helping.
