### ISSUE TITLE
Where is lookupaddresses management command?

### ISSUE THREAD

**Issue by jplehmann** [furious-luke/django-address#32]
Docs specify: "You will need to run the lookupaddresses management command".

When I run "manage.py --help" I don't see this option, nor do I see it in the source.

I am using the dev branch.

**Comment by furious-luke** [comment]
Yep, that command is only necessary in unusual circumstances, as noted in the docs. You shouldn't really need it.

But, yep, I will push in the actually management command soon.

**Comment by furious-luke** [comment]
Okay, the `lookupaddresses` command is now available. You should only need to use if you find you have addresses that have not been geocoded. This tends to happen if you run out of Google geocode requests.

**Comment by jplehmann** [comment]
Thank you.
