### ISSUE TITLE
Autocomplete broken: $this.geocomplete is not a function

### ISSUE THREAD

**Issue by jplehmann** [furious-luke/django-address#33]
When it try to render a form with the Address field, the console shows:
`Uncaught TypeError: $this.geocomplete is not a function`
and thus autocomplete does not work.

Also, less important but easy to fix, the Sensor parameter is no longer required:
`Google Maps API warning: SensorNotRequired: https://developers.google.com/maps/documentation/javascript/error-messages`

**Comment by furious-luke** [comment]
The autocomplete on the example site in `exampes/example_site` seems to be working properly. A typical cause for this kind of error is not including the `geocomplete` JavaScript file. Did you use the `form.media` method of including the JavaScript, or are you doing it manually?

**Comment by jplehmann** [comment]
I used form.media, and upon examining the HTML source I see this in the
head:

```
<script src="
https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" src="
https://maps.googleapis.com/maps/api/js?libraries=places&amp;sensor=false
"></script>
<script type="text/javascript"
src="/static/address/js/jquery.geocomplete.js"></script>
<script type="text/javascript"
src="/static/address/js/address.js"></script> <!-- needed for JS/GoogleMaps
lookup -->```

However I am also already including Jquery at the bottom of my body. Could
this be interfering?

On Fri, Jan 8, 2016 at 3:34 PM, Luke Hodkinson <notifications@github.com>
wrote:

> The autocomplete on the example site in exampes/example_site seems to be
> working properly. A typical cause for this kind of error is not including
> the geocomplete JavaScript file. Did you use the form.media method of
> including the JavaScript, or are you doing it manually?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/furious-luke/django-address/issues/33#issuecomment-170134094>
> .
>

**Comment by jplehmann** [comment]
Yea as soon as I move this below to the bottom of the body, below where I
import my own JQuery (1.x) it works.

**Comment by furious-luke** [comment]
Okay, no problems. I'll add a section to the documentation about using your own jQuery.

**Comment by jplehmann** [comment]
Hi Luke, you might answer this in your docs about custom JQuery, but here's where I'm currently stuck at: I am using JQuery version 1.11.3 just for maximum compatibility across devices etc.  This gets run first.  I then run Bootstrap's JQuery plugin.  Finally I include django-address media tag, which brings in:
```
<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;sensor=false"></script>
<script type="text/javascript" src="/static/address/js/jquery.geocomplete.js"></script>
<script type="text/javascript" src="/static/address/js/address.js"></script>
```
It appears to be running a local version of JQuery which its installed in my static path.  (Note I didn't even include the explicit call to JQuery 2 which your dev-branch only docs show).

The net effect is I get some errors from later calls to the Bootstrap plugin (popover and collapse) which are not known.  Clearly this is caused somehow by multiple JQuery versions, but I don't have a lot of depth here.

Questions:
1. Many of your users will already have JQuery so do you want to include it by default as you are doing or does it make more sense to have them include it explicitly like your docs showed in the dev branch?  
2. Would django-address and its dependencies work properly with JQuery 1.x? I am happy to test that out.

**Comment by furious-luke** [comment]
The `media` approach to including JavaScript is useful for basic needs, but if you wish to include your own versions of plugins you'll need to include all the JavaScript manually, not using `media`.

I've not tested against jQuery 1.x, it really comes down to whether `jquery.geocomplete` can handle it. Certainly the `django-address` JavaSript would be fine with jQuery 1.x, as it's nothing more than a simple function call.

**Comment by jplehmann** [comment]
Ah ya, that is obvious I guess.  Works perfectly (don't see a problem with
1.x).  Thanks!

**Comment by jplehmann** [comment]
I'll let you close this once you add whatever documentation you wanted to.

**Comment by banagale** [comment]
I'm going to close this, since this is very old and I do not know if we will want to require jquery in 0.3.0.
