### ISSUE TITLE
Would like to make address optional and/or custom error message

### ISSUE THREAD

**Issue by jplehmann** [furious-luke/django-address#35]
I am concerned about users typing in an address such as "usa" (lowercase) and not selecting an autocomplete option, so I wanted to provide a more specific message than "Invalid value".  At first I tried to set `required=False` and planned on customizing `clean_address` however this did not work since AddressField's to_python always raises.

To work around, I subclassed `AddressField`:
```
class CustomMessageAddressField(AddressField):
    def to_python(self, value):
        from django.core.exceptions import ValidationError
        try:
            val = super(CustomMessageAddressField, self).to_python(value)
        except ValidationError:
            raise ValidationError("Please enter a location and choose from the displayed list of options.")
        return val
```

I'm not sure how the `required` field is supposed to work but seems like `to_python` should only fail if this is True.  Also some others might actually want to make the address field not required.

All of this might be a 1 line change, but I defer to Luke on how to best address it.  No pun intended.

The other validation step I'm adding is requiring at least a city to be provided. This potentially could be another set of flags that might be generally useful.
```
    def clean_address(self):
        from address import kinds
        address = self.cleaned_data.get('address')
        cities = address.filter_kind(kinds.KIND_LOCALITY)
        if not cities:
            raise forms.ValidationError("Please provide at least a city and country")
        return address
```

**Comment by furious-luke** [comment]
Hmmm, it sounds like a bug to me. The system should allow for non-geolocated addresses, just in case there are some addresses that Google just doesn't know about. I'll look in to it.

**Comment by furious-luke** [comment]
P.S. Thanks a million for all the bug reports, it's immensely helpful!

**Comment by jplehmann** [comment]
Man, thank YOU!  I am grateful and excited to be using a library, of an
owner who is so amazingly responsive.

I am about to roll this out tomorrow, and am working on the "Breeder Map"
which the users are going to love. Will let you know when I do so you can
see how it's paying off!

**Comment by furious-luke** [comment]
Okay, I've pushed some changes to correct this issue. You should now be able to store non-geolocated addresses, and the form should react correctly to setting `required`.
