### ISSUE TITLE
Failure to deploy with django-pipeline: missing Bootstrap resources

### ISSUE THREAD

**Issue by jplehmann** [furious-luke/django-address#36]
Trying to deploy on Heroku is failing because of a missing font file 'fonts/glyphicons-halflings-regular.eot' that is referenced from bootstrap. Nevermind that django-address doesn't really need this file.

At first I thought the dependency was due to the autocomplete, but I actually can't find any reference to bootstrap in all of the library.

```
remote:     output = self.handle(*args, **options)
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
remote:     collected = self.collect()
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 120, in collect
remote:     raise processed
remote: ValueError: The file 'fonts/glyphicons-halflings-regular.eot' could not be found with <mysite.custom_storages.S3PipelineManifestStorage object at 0x7fdacaf69b50>.
```

**Comment by jplehmann** [comment]
And in any event, I already use Bootstrap so if it were required it'd be nice to provide my own.

**Comment by furious-luke** [comment]
I've eliminated bootstrap from the static files. It's been lingering around in there since day 1, so is good to finally clean it up.
