### ISSUE TITLE
Why are there many fields if finally I will have to write everythin again in RAW?

### ISSUE THREAD

**Issue by cfoch** [furious-luke/django-address#38]

**Comment by furious-luke** [comment]
Hi there,
The `raw` field is needed for failed geocoding attempts. The idea is that most addresses will be entered by users in a form, and automatically geocoded by Google. Sometimes, however, the geocode fails, so we need to be able to store the raw address so an admin can later figure out why it failed to be located.
Cheers,
Luke

**Comment by jplehmann** [comment]
Close.

**Comment by banagale** [comment]
@cfoch Thank you for this report.

@furious-luke is correct, although there are situations where you may want to assemble and write the raw field from the currently available components.

I've added a note about considering a method to set the raw field from existing address components [here](https://github.com/furious-luke/django-address/wiki/django-address-Model-Notes).

Closing as answered.
