### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one Address -- it returned 5!

### ISSUE THREAD

**Issue by jplehmann** [furious-luke/django-address#42]
Hi Luke,

When a user enters the location "Columbus, Ohio, USA", this exception raises during form validation.  "Dayton, OH, USA" however does not cause such a problem.  I've seen the number returned vary from 3 to 5.

```
Internal Server Error:
Traceback (most recent call last):
...
  File "/app/mysite/snakes/views.py", line 1485, in edit_store
    if form.is_valid():
  File "/app/.heroku/python/lib/python2.7/site-packages/django/forms/forms.py", line 184, in is_valid
    return self.is_bound and not self.errors
  File "/app/.heroku/python/lib/python2.7/site-packages/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/forms/forms.py", line 392, in full_clean
    self._clean_fields()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/forms/forms.py", line 407, in _clean_fields
    value = field.clean(value)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/forms/fields.py", line 162, in clean
    value = self.to_python(value)
  File "/app/.heroku/python/lib/python2.7/site-packages/address/forms.py", line 98, in to_python
    return to_python(value)
  File "/app/.heroku/python/lib/python2.7/site-packages/address/models.py", line 192, in to_python
    return _to_python(value, instance, address_model, component_model)
  File "/app/.heroku/python/lib/python2.7/site-packages/address/models.py", line 145, in _to_python
    'consistent': consistent,
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 405, in get_or_create
    return self.get(**lookup), False
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one Address -- it returned 5!
```

I do have a bit of custom cleaning logic, which I do not think is related:

```
    def clean_address(self):
        address = self.cleaned_data.get('address', None)
        if not address:
            raise forms.ValidationError("Location is a required field")
        if not address.formatted:
            raise forms.ValidationError("Please choose from known list of locations that is shown while you type")
```

and

```
    def clean(self):
        cd = self.cleaned_data
        # Set the country value based on address
        address = cd.get('address')
        if address:
            from django_countries.fields import Country
            countries = address.filter_kind(kinds.KIND_COUNTRY)
            assert countries, "Found no country in address: {}".format(address)
            cd['country'] = Country(code=countries[0].short_name)
```

**Comment by jplehmann** [comment]
I am also seeing duplicate looking address entries in my address table. Not sure if this is the cause or an effect. I see at least 2 more on the same page as well.

![screen shot 2016-02-24 at 8 42 07 am](https://cloud.githubusercontent.com/assets/460964/13288653/91d50fcc-dad2-11e5-8cf8-56b30292e014.png)

**Comment by furious-luke** [comment]
Thanks for the report, I'll look in to it first thing this morning.

**Comment by furious-luke** [comment]
Hi again John,

Okay, firstly, yep, it's the duplicate addresses that are causing the problem. I've updated the code to prevent the error and use one of the existing duplicates (and prints a verbose warning). Your users should be able to enter addresses that have duplicates now.

I ran a bunch of tests and it looks like the code does prevent duplicates *after* migrations have been run. This indicates the duplicates were most likely introduced during your initial migration. I'll need to analyse the migration code and figure out where this is happening to prevent it occurring again for other migrations.

In the mean time, I'll write a helper piece of code to assist in removing duplicates, but you'll need to your own hook into the code so we can update any other models you may have that refer to the duplicates. I'll keep you posted.

Cheers,
Luke

**Comment by jplehmann** [comment]
Hi Luke,

I'm now using the head on develop and it appears to have fixed this issue.

Two questions:
1. Also, any update on that piece of helper code?
2. Do you think we'll be on master in the foreseeable future?

thanks!
John

**Comment by furious-luke** [comment]
Hi John,

Sorry, I haven't looked at the helper code yet. :(   I'll hopefully get some time to take a look over the next week or two.

I've been thinking of splitting the develop branch off into a separate repository. It's diverged quite a lot from the master branch, and I'm not sure I should force users into moving to what is a very different system.

Cheers,
Luke

**Comment by jplehmann** [comment]
No problem, I don't think the current (unmerged status) is causing any problems.

What you're suggesting is a major version change with a migration path or a completely separate project with no migration path?   My only concern would be creating more independent projects that you are trying to maintain in your limited time, but I can see how it could be less work overall.

**Comment by banagale** [comment]
Since the underlying issue related to this is handled, closing this.  I do see the additional references to the `dev` vs `master` situation.
