### ISSUE TITLE
Use django-countries as a backend

### ISSUE THREAD

**Issue by jgeerds** [furious-luke/django-address#44]
Is there a specific reason why `django-address` doesn't use [django-countries](https://pypi.python.org/pypi/django-countries) for the Country model? The package ships all known countries including ISO-3166-1 codes

**Comment by furious-luke** [comment]
All the information about countries is automatically collected from Google's geocoding services. Having all the countries already stored locally wouldn't really give much of a benefit (and may actually be a problem if there are any inconsistencies between `django-countries` and Google's database); it's easier to allow Google to furnish the app with all the data needed.

**Comment by jgeerds** [comment]
Ah, that makes sense! Thanks
