### ISSUE TITLE
Error when querying anything in Mexico

### ISSUE THREAD

**Issue by cesarmanzo** [furious-luke/django-address#50]
When querying a location in Mexico, it always fails because the state code is larger than 3 digits.

E.g., when searching for "Alberto Carrera Torres, Guadalupe, Cerritos, México" it shows the error:

`Invalid state code (too long): S.L.P.`

I think that it is showing states abreviation instead of the 3-digit state codes. See here:
https://en.wikipedia.org/wiki/Template:Mexico_State-Abbreviation_Codes

Can't see anywhere in the response where I can get that 3-digit state code.

**Comment by cesarmanzo** [comment]
If you want to see the response from Google, look at this example:

https://maps.googleapis.com/maps/api/geocode/json?address=San%20Luis%20Potosi

It seems like Google is in the wrong on this one, but still doesn't work properly because of this. Maybe rising the max_length on the field will be a good temporary solution until Google gets its things together.

Here is another example:

https://maps.googleapis.com/maps/api/geocode/json?address=Chihuahua

**Comment by banagale** [comment]
@cesarmanzo Thank you for the report.

Related to #82. Hoping to address in [0.2.3](https://github.com/furious-luke/django-address/milestone/3).

Here's a sample JSON response from Google of San Luis Potosi:

[{
	"address_components": [{
		"long_name": "San Luis Potos\\u00ed",
		"short_name": "San Luis Potos\\u00ed",
		"types": ["locality", "political"]
	}, {
		"long_name": "San Luis Potosi",
		"short_name": "S.L.P.",
		"types": ["administrative_area_level_1", "political"]
	}, {
		"long_name": "Mexico",
		"short_name": "MX",
		"types": ["country", "political"]
	}],
	"formatted_address": "San Luis Potos\\u00ed, San Luis Potosi, Mexico",
	"geometry": {
		"bounds": {
			"northeast": {
				"lat": 22.2186053,
				"lng": -100.8561164
			},
			"southwest": {
				"lat": 22.0068338,
				"lng": -101.0560226
			}
		},
		"location": {
			"lat": 22.1564699,
			"lng": -100.9855409
		},
		"location_type": "APPROXIMATE",
		"viewport": {
			"northeast": {
				"lat": 22.2186053,
				"lng": -100.8561164
			},
			"southwest": {
				"lat": 22.0068338,
				"lng": -101.0560226
			}
		}
	},
	"place_id": "ChIJefusBQCiKoQRV4Lhrynu0g4",
	"types": ["locality", "political"]
}]

**Comment by banagale** [comment]
Questions:

 - Why is state code limited to two characters?
 - Any tests related to this limitation?
 - How many letters does google return at a maximum?

**Comment by banagale** [comment]
- Reproduce failure to accept San Luis Potosí
 - Update models.py
 - Make migrations
 - Update tests as necessary

**Comment by banagale** [comment]
Fixed in https://github.com/furious-luke/django-address/commit/9cbe682994a2d176485c2f5adb600042c7a5bf57 and subsequent typo-rectifying commit.
