### ISSUE TITLE
Using the Wrong Google Maps API

### ISSUE THREAD

**Issue by robinspollak** [furious-luke/django-address#54]
After reading the usage limits and billing page of the API that this library uses (https://developers.google.com/places/web-service/usage?hl=en_US) it seems that instead this library should use the google maps javascript API. (https://developers.google.com/maps/documentation/javascript/places)

**Comment by banagale** [comment]
It appears that since this issue was filed, the two libraries now use the same quota:

> The Places Library, JavaScript API shares a usage quota with Places API as described in the Usage Limits documentation for Places API. The queries per second rate limit is applied per user session, regardless of how many users share the same project.*
