### ISSUE TITLE
Localities are assigned the wrong zip/postal code

### ISSUE THREAD

**Issue by matthewslaney** [furious-luke/django-address#56]
In an attempt to reuse Localities, the wrong zip code is assigned if the city name matches. For example:

First lookup returns result of: 123 Any Rd, Mytown, CA 90210, United States

Second lookup returns result of: 345 Some Dr, Mytown, CA, 90211 United States

When the second address is added, it attaches itself to the existing "Mytown", and that Mytown shows a zip code of 90210. The Raw and Formatted fields have 90211, but the foreign key to locality implies the wrong zip code.

**Comment by furious-luke** [comment]
Fixed by #41
