### ISSUE TITLE
Google API now requires an API key and will not run at all with it

### ISSUE THREAD

**Issue by matthewslaney** [furious-luke/django-address#57]
The API key, or rather lack thereof, is hardcoded into the forms.py for the module. This should be changed so that there is an option to assign it via the project's settings.py.

**Comment by brenoarosa** [comment]
Can we get an update in this? There is 3 pull request fixing it already.

**Comment by andreyshipilov** [comment]
Bump?

**Comment by banagale** [comment]
Thank you @matthewslaney, @brenoarosa and @andreyshipilov.

This was handled in pull/59. Please see #98 for recent updates on `django-address`.
