### ISSUE TITLE
Missing components?

### ISSUE THREAD

**Issue by oboingo** [furious-luke/django-address#60]
When running Django from the dev server, when the lookup works fine, or when I run "manage.py lookupaddresses", either way, the address only gets one component, the street number.  The other components are listed under 'Available components', but are not added to the 'Chosen components'.  I can add them manually, but that really isn't a good solution for 10,000+ addresses.  Am I doing something stupid?

Perhaps related, when I added two addresses in the same postal_code, the postal_code is listed in components twice, even though neither of them were added to the 'Chosen components'.  Shouldn't the postal_code only be added to the components once?

**Comment by banagale** [comment]
I believe this is referencing some management command that is unexplained. Closing as no longer relevant or invalid. @oboingo Feel free to re-open if this is still an issue and you can explain it more thoroughly.
