### ISSUE TITLE
Jquery lookup behind Apache?

### ISSUE THREAD

**Issue by oboingo** [furious-luke/django-address#61]
When running Django from the dev server, the jquery works in the Django admin and does the lookup seemingly correctly.  "Powered by Google" and everything.   But.... when I run it from behind Apache with WSGI, I get "Google Maps API error: MissingKeyMapError" and the lookup never happens.  I did collectstatic.  What else could I be doing wrong?

**Comment by bendog** [comment]
@oboingo it's because the Google maps API now REQUIRES an API key, see bug #57

**Comment by banagale** [comment]
Since it is now well documented by Google that the Google Maps API requires an API key, I"m closing this issue.
