### ISSUE TITLE
Multiple zip codes in one locality

### ISSUE THREAD

**Issue by cassidylaidlaw** [furious-luke/django-address#63]
One locality can have a number of zip codes; for instance, New York City has all zip codes of the form 100xx–104xx, 11004–05, 111xx–114xx, and 116xx. Also, sometimes people add an extra four digits to the end of the zip code to indicate a more specific location. The current implementation ties zip codes to localities and doesn't allow one locality to have multiple zip codes.

**Comment by jplehmann** [comment]
Seems related to an issue I created a while ago, although that was more of a lookup issue, and you're pointing out a design issue.

https://github.com/furious-luke/django-address/issues/34#issuecomment-170404067

A less related zipcode issue: Localities are assigned the wrong zip/postal code #56

**Comment by furious-luke** [comment]
PR #41 will ensure a unique locality will be generated for each combination of locality name and zip code.

**Comment by explody** [comment]
I'll actually take this a bit further and say that postal codes should not be tied to locality at all.  Postal codes are _national_ constructs that overlay with the boundaries of metro areas.  

The side effect here is that a large city like Los Angeles has > *900* zip codes which means one would end up with potentially hundreds of "Los Angeles, California, USA" entries just for separate zip codes - but the zips are *inside* Los Angeles, not the other way around - one city, many postal codes.

It seems like postal code should really just be an attribute of 'Address'.  Or am I missing something about the design approach?

**Comment by banagale** [comment]
While the original issue described by @cassidylaidlaw has been resolved in pull/41, @explody 's structural question is still valid.

I'm closing this issue as completed, however I have made a note about considering refactoring postal code out of locality in a future release [here](https://github.com/furious-luke/django-address/wiki/Address-Model-Notes#postal-code-tied-to-locality).  Please see #98 for updates on `django-address`
