### ISSUE TITLE
Installing the app via pip with django version 1.10 errors

### ISSUE THREAD

**Issue by jamesaud** [furious-luke/django-address#64]
If this is repeatable by someone, let me know.

Installing via pip and adding to the INSTALLED_APPS='address' works.

However, running python manage.py migrate causes an error that says something like:
"Country in not in INSTALLED_APPS"

**Comment by banagale** [comment]
Since it has been three years and I have not seen duplicates of this issue, I'm closing it as invalid. Please re-open if it is still known.
