### ISSUE TITLE
Python 3 & Django 1.7 Compatibility

### ISSUE THREAD

**Issue by DylanLukes** [furious-luke/django-address#7]
I'm opening an issue to bring attention to my fork. I've added Python 3 support (via six) and merged in the 1.7 fixes. I'm currently testing it out, but it should be most of the way there. 

Here's a link: DylanLukes@9d41b544497089153e9fe982638d567e9902ce8e

If it checks out I'll submit a pull request.

**Comment by furious-luke** [comment]
Hi Dylan,
I've just pushed in some commits that provide Python 3 support, I'll close this issue now but please feel free to reopen it if you find there is still something missing. Thanks for your efforts with this!
Cheers,
Luke
