### ISSUE TITLE
django 2.0, missing 1 required positional argument: 'on_delete'

### ISSUE THREAD

**Issue by darahsten** [furious-luke/django-address#76]
File "/home/user/.virtualenvs/rola/lib/python3.5/site-packages/address/models.py", line 171, in State
    country = models.ForeignKey(Country, related_name='states')
TypeError: __init__() missing 1 required positional argument: 'on_delete'. 
Django 2.0 requires on_delete to be explicitly set. Hence using this with django 2.0 results in the above missing positional argument.

**Comment by fatk1d** [comment]
There was a recent pull request merged into master that appeared aimed at fixing this issue and other issues related to Django 2.0 and Python 3.6.0 but it didn't seem to catch everything when I worked with it.  Considering submitting another pull request for consideration myself.  Not completely sure that I'm doing everything correctly but I did manage to get it working.

**Comment by yaplej** [comment]
I'm having this issue too.  Getting close to another release to pypi?
https://github.com/furious-luke/django-address/issues/72

**Comment by karbassi** [comment]
Fixed in #78

**Comment by karbassi** [comment]
@smobbl-bobbl: We're waiting for @furious-luke to push a new version of this package. v0.1.7 should have this fix.
