### ISSUE TITLE
The address field returns None

### ISSUE THREAD

**Issue by rubenmafe** [furious-luke/django-address#86]
When I'm trying to create a Address by default de Address value is None. This is because it has changed widgets.py line 76 for escape(). Escape() returns None but with a bad type. The previous version, 0.2.0. works well.

**Comment by alagirirajesh** [comment]
Hi @rubenmafe how do you correct this issue. please advice. What is the change that needs to go in?

**Comment by blocher** [comment]
I've made a PR with one possible fix for this issue: https://github.com/furious-luke/django-address/pull/90

Change line 80 of `address\widgets.py` to `escape(ad.get('formatted', '')),`

**Comment by moritz89** [comment]
A work-around until it is merged and released is to use the following code:

    from django import forms
    from address.forms import AddressField
    
    class MyForm(forms.Form):
        address = AddressField(initial={'formatted': ""})

**Comment by banagale** [comment]
Thank you for the report, and workaround @moritz89.

Closing as a duplicate of #89 which has a PR.
