### ISSUE TITLE
Getting 'on_delete' error 

### ISSUE THREAD

**Issue by Alexmhack** [furious-luke/django-address#88]
Getting error **TypeError: __init__() missing 1 required positional argument: 'on_delete'** when running with django2, there has some issues related to this and seems like this has been solved and package is compatible with django2 but then too I am getting the same error.

Any suggestions ??

**Comment by Mustafa-C** [comment]
Any updates on this?

**Comment by PLsergent** [comment]
https://github.com/furious-luke/django-address/issues/80

Go check this ticket
