### ISSUE TITLE
Cannot get placeholder to show in address field (Address field is None)

### ISSUE THREAD

**Issue by samkamin** [furious-luke/django-address#89]
The example site works fine, but in my own site, the address field always shows up initially with value None, instead of the placeholder ("Enter a location").  If the user deletes the None, then the placeholder shows up, but I can't get it to show up initially.

Details:  (django v. 2.2, not sure what version of address, but it's a pretty recent download)

First, the example site works.  Just to be more similar to my site, I changed line 13 in person/views.py to

`form = PersonForm()`

Then, in person/forms.py, I can change line 8 to either of these:

```
   address = AddressField()      # shows placeholder
   address = AddressField(initial=Address.objects.first())   # shows address from db
```

Iow, everything works.  (In the first case, the html, as shown in the browser debug window, does not have the `value` attribute set.)

Now, my site.  I can get the address from the db, but no matter what I've tried, the value field in the html is always set to None, and that is what shows up in the input field.  Here are a few examples of what I've tried; these are lines from my users/forms.py, in the initialization of CustomUserCreationForm (subclass of UserCreationForm):

```
address = AddressField(initial=Address.objects.first())   # shows address from db
address = AddressField()  # shows 'None' in form
address = ''  # not sure why this works at all, but it also shows 'None'
address = AddressField(initial='')  # again, shows 'None'
address = AddressField(initial=Address())  # I thought this might create some empty address
                                  #  object and that would be good, but again it shows 'None'
```
Fundamentally, *someone* is insisting on setting the value attribute in the html, and so that overrides the placeholder.  I don't know why it would be this app (since it doesn't happen in the example site), but it doesn't happen in any other fields, so I'm stuck.  Any suggestions?

(One more detail:  The field in the model is created just like in example site: `address = AddressField(on_delete=models.CASCADE)`)

**Comment by samkamin** [comment]
Okay, I figured this out.  I think it's something that should be fixed in the code, but I'm not confident enough of my analysis to do that.  I'm going to leave this open for a few days and see if there's any response, and then close it.

I was wrong about the example site working; I was testing it by reloading the page, but that just resends the most recent POST request.  The problem is that an initial GET request, with a blank form, does not show the place holder, but instead shows the word None.  The reason is address/widgets.py, l. 77-84:

        elems = [
            super(AddressWidget, self).render(
                name,
                escape(ad.get('formatted', None)),
                attrs,
                **kwargs
            )
        ]

and more specifically, the middle line (80), `escape(ad.get('formatted', None))`.  For a GET request, the call to render from person/views.py has an empty value; so `ad` is the empty dictionary, and the `ad.get(..)` call returns None.  But `escape` turns that into the *string* 'None'.  The super call interprets this as a legit value, and we get `value="None"` in the html.

Obvious solution is to change line 80 to something like:

    None if ad=={} else escape(ad.get('formatted', None)),

(In the meantime, I'm using the ugly workaround of subclassing AddressWidget, defining render to call AddressWidget.render and stripping the "value=..." out of the string.)

**Comment by blocher** [comment]
I've made a PR with one possible fix for this issue: https://github.com/furious-luke/django-address/pull/90

Change line 80 of `address\widgets.py` to `escape(ad.get('formatted', '')),`

**Comment by banagale** [comment]
@samkamin Thank you for the report and @blocher for the PR.

I've slated this for the second triage release, but may move it up to this coming release if possible.

**Comment by banagale** [comment]
Completed in #90
