### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by furious-luke** [furious-luke/django-address#94]
Hi all! As is patently clear, I'm not able to find the time to maintain this project. In the past I've reached out to individuals who have been active in submitting issues and PRs to seek maintainers, but unfortunately they too have shared my lack of time.

If anyone feels they would like to become a maintainer for this project, please let me know.

Thanks,
Luke

**Comment by aborsu** [comment]
Hello, 

I don't have a very visible open source contribution as I work in enterprise, but I have a lot of experience building and maintaining python packages. I am using your package in two projects and I can spare a bit of time triaging issues and publishing the package to pypi.

**Comment by furious-luke** [comment]
Hey @aborsu, that would be a massive help, thank you!

**Comment by aborsu** [comment]
@furious-luke  I'm really sorry, a few life altering changes happened and I was not able to follow through on the invite, could you invite me again and I'll get to work.

**Comment by furious-luke** [comment]
@aborsu Sure thing!

**Comment by banagale** [comment]
@furious-luke Hey Luke, I do not have a lot of experience building and maintaining python packages. 

However, I have a good deal of experience with Django and have been looking for an open source project to assist in maintaining. 

I can help with PR reviews, interaction around issues and look to offer original PRs when needed. This might pair well with @aborsu to spread the work out a bit.

**Comment by furious-luke** [comment]
Thanks for your offer of help @banagale, it's very much welcome!

@aborsu, if you could get in touch via email I'd be happy to introduce you to @banagale ?
